<?php $this->layout('layouts/layout') ?>

<?php $this->section('content') ?>

<div class="section no-pad-bot" id="index-banner">
      <div class="container">
         <br><br>
         <h1 class="header center orange-text">Welcome</h1>
         <div class="row center">
            <h5 class="header col s12 light">A lightweight modern PHP framework inspired by ASP.NET Core.</h5>
         </div>
         <div class="row center">
            <a href=# id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
         </div>
         <br><br>
      </div>
</div>

<?php $this->endSection() ?>
