<?php $this->layout('layouts/layout') ?>

<?php $this->section('content') ?>

<div class="section no-pad-bot" id="index-banner">
   <div class="container">
      <br><br><br>
      <div class="text-center">
         <h1 class="text-info display-3">Welcome</h1>
         <p>To a modern lightweight PHP framework inspired by ASP.NET Core.</p>
         <a class="btn btn-info" href="https://devnet-framework.github.io">Get Started</a>
      </div>
      <br><br>
   </div>
</div>

<?php $this->endSection() ?>
