<!DOCTYPE html>
<html lang="en">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
   <title>Atrister - DevNet Framework</title>
   <!-- CSS  -->
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
   <link href="<?= url('css/materialize.min.css') ?>" type="text/css" rel="stylesheet" media="screen,projection"/>
   <link href="<?= url('css/style.css') ?>" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
   <header>
      <?php $this->renderPartial('layouts/navbar') ?>
   </header>
   <main>
      <?php $this->renderSection('content') ?>
   </main>

  <!--  Scripts-->
  <script src="<?= url('js/materialize.min.js') ?>"></script>
  <script src="<?= url('js/script.js') ?>"></script>
  </body>
</html>