<nav class="navbar white" role="navigation">
    <div class="nav-wrapper container">
        <a id="logo-container" href="<?= url('/') ?>" class="brand-logo orange-text">DevNet</a>
        <ul class="right hide-on-med-and-down">
            <li><a href="<?= url('/') ?>">Home</a></li>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-trigger" href="" data-target="dropdown-login">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        <ul id="nav-mobile" class="sidenav">
                <li><a href="<?= url('/account/login') ?>">Log In</a></li>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
</nav>
<!-- Dropdown Structure -->
<div id="dropdown-login" class="dropdown-content">
    <ul>
        <li><a href="<?= url('/account/login') ?>">Login<span class="material-icons right">lock</span></a></li>
        <li class="divider"></li>
        <li><a href="<?= url('/account/register') ?>">Register</a></li>
    </ul>
</div>