<?php $this->layout('layouts/layout') ?>

<?php $this->section('content') ?>

<br><br><br>
<div class="text-center">
      <h1 class="text-info display-3">Hello!</h1>
      <h5 class="text-info"><?= $this->ViewData['Email'] ?></h5>
      <p>Click on the log out button to close your session.</p>
      <a class="btn btn-info" href=<?= url('/account/logout') ?>>Log Out</a>
</div>
<br><br>

<?php $this->endSection() ?>
