<?php $this->layout('layouts/layout') ?>

<?php $this->section('content') ?>

<div class="container-card">
	<div class="row card hoverable z-depth-2">
		<div class="card-content ">
		   <h4 class="center blue-text">Login</h4>
		   <form class="row s12" method="post" action="<?= url('/account/login') ?>">
            <div class="row">
               <div class="input-field col s12">
                  <input type="email" id="email" name="Email" class="validate" required>
                  <label for="email">User Email</label>
               </div>
            </div>
            <div class="row">
               <div class="input-field col s12">
                  <input type="password" id="password" name="Password" class="validate" required>
                  <label for="password">Password</label>
               </div>
            </div>
            <div class="row">
               <div class="input-field col s12 center">
                  <button type="submit" class="btn waves-effect waves-light blue" style="width: 100%">Login<i class="material-icons right">send</i></button>
               </div>
            </div>
            <div class="row">
               <div class="col s6">
                  <label>
                     <input type="checkbox" name="Remember" value="false"/>
                     <span>Remember me</span>
                  </label>
               </div>
               <div class="col s6 right-align">
                  <a href=#>Forgot password?</a>
               </div>
            </div>
         </form>
      </div>
   </div>
   <div class="center">
      <a href=<?= url('/account/register') ?>>Register new account</a>
   </div>
</div>

<?php $this->endSection() ?>
